### ISSUE TITLE
[W7-Kaggle-competition] Cristian Castro Blua

### ISSUE THREAD

**Issue by ccastroblua** [Ironhack-Data-Madrid-Mayo-2021/W7-Kaggle_competition#1]
https://github.com/ccastroblua/kaggle_competition

**Comment by sheriffff** [comment]
- Echo de menos un poco de exploratory analysis para entender las variables. Algún countplot, histogramas...
- Buen engineering para pasar categóricas a numéricas. Todas tenían sentido de orden y así las trataste ;)
- Bien probados varios modelos para elegir el mejor.
- Muy bien utilizado el train test split para hacernos una idea antes de las submissions.

Y ganaste la competición, enhorabuena!!
