### ISSUE TITLE
[W7-Kaggle_competition] - Alvaro Garcia Blazquez

### ISSUE THREAD

**Issue by alvarogb1919** [Ironhack-Data-Madrid-Mayo-2021/W7-Kaggle_competition#2]
link: https://github.com/alvarogb1919/Diamond-competition

**Comment by sheriffff** [comment]
Buen proceder en general
- Un poco de Exploratory analysis siempre viene bien para entender las variables. Algún countplot e histplot estarían bien.
- Buen feature engineering para cambiar las variables categóricas por numéricas. Echo de menos la tercera variable categórica tratada.
- Bien utilizados regresión lineal, decision tree, grid search...
- No me haces train test split! Y deberías evalúuar el resultado en el train y test con `mean_squared_error` o similar para tener una idea del resultado antes del submission.
